### ISSUE TITLE
Square method has no test coverage

### ISSUE THREAD

**Issue by casto101** [roguerb/pull-request-workshop#11]
I saw there's a new `square` method in `rogue_math.rb`, but there's no corresponding test coverage. It could use some specs.

**Comment by conroywhitney** [comment]
Hey @casto101. Thanks for pointing this out!

I'm assuming you're referring to e5c25db0a9607d765f0e6fa84d6eb703ed13c88b so I'm CC'ing @seanculver.

Would one of you add some specs for the `square` method. And for goodness sakes, let's use some examples _besides_ `2` and `2`. That keeps biting us in the butt with these other methods.

Thanks!

**Comment by seanculver** [comment]
Doh, did I forget to do that?

**Comment by seanculver** [comment]
@casto101 I'm out of town for the weekend, going to the beach with the family, I won't have time to fix this, but I'd be happy to merge a PR.

Thanks!

**Comment by conroywhitney** [comment]
Closed by #23. Thanks everyone!
