### ISSUE TITLE
Subtract method is painfully counterintuitive

### ISSUE THREAD

**Issue by mistertime** [roguerb/pull-request-workshop#12]
I'd say we all agree that `strcpy` was a mistake, yes? Let's not perpetuate such horrors. The subtract method subtracts the first argument from the second, a grievous infraction against common English syntax and, by extension, the majority of programming conventions.

**Comment by conroywhitney** [comment]
Haha @mistertime. That's awesome. Thanks for pointing that out.

Would you mind creating a Pull Request that fixes that method, as well as updates the specs so that this issue doesn't crop up in the future?

Thanks!

**Comment by conroywhitney** [comment]
Closing this Issue after merging in the project's Code of Conduct in PR #20. While the content of this issue is valid (these methods are wrong), the way it is phrased violates the new Code of Conduct, specifically in regards to "disparaging personal remarks".

We'll open a new issue.
