### ISSUE TITLE
Divide method is miserably preposterous

### ISSUE THREAD

**Issue by mistertime** [roguerb/pull-request-workshop#13]
In a manner distastefully similar to #12, the `divide` method is nauseatingly badly implemented&mdash;the second argument is divided by the first, which is, once again, an abominable violation of common English syntax.

At this point, I must inquire as to your qualifications&mdash;the nature of these heinous crimes against commonly accepted syntax inclines me to believe that you and whoever wrote `strcpy` must have attended the same university.

**Comment by seanculver** [comment]
All laughs aside, you'll never get code merged if you insult the maintainers.

**Comment by conroywhitney** [comment]
Hey @mistertime. Thanks for pointing this out.

Similarly to #12, would you mind creating a PR that addresses this issue as well as creates specs to ensure we don't run into this bug in the future?

And actually, now that I think about it, that method is dangerous for another reason -- the dreaded divide by zero error. While you're in there, think you could add some tests / guard clauses to beef up that whole part of the code?

Thanks!

**Comment by programmin1** [comment]
Dreaded divide by 0 quits the program in Ruby! Maybe it should be like PHP and just throw a warning:

```
$ php -a
Interactive mode enabled

php > echo 3/0; echo 'hi'.'there';
PHP Warning:  Division by zero in php shell code on line 1
hithere
```

Equivalent Ruby cause error and quits.

Maybe divide by 0 should return UNSINGEDINFINITY constant.

**Comment by conroywhitney** [comment]
Haha. Maybe we should just port this whole project over to `PHP`  😁

**Comment by mistertime** [comment]
Should we switch to another language, it should obviously be Beeswax.

**Comment by conroywhitney** [comment]
@mistertime -- there's a discussion on implementing a Code of Conduct on this project over in Issue #17 if you want to weigh in on the decision.

I have no doubt you are just being comical; however, depending on what direction we go, the language in this PR might be construed as inappropriate and we'd have to address it.

I'd love to get your thoughts over in Issue #17.

Thanks!

**Comment by conroywhitney** [comment]
Closing RE: #20's new Code of Conduct. While the content of this issue is correct (the methods are broken), the words used violate the Code of Conduct, specifically with regards to "disparaging personal remarks".

We'll open a new issue to start over after adopting the CoC.
