### ISSUE TITLE
Adopt a Contributor Code of Conduct

### ISSUE THREAD

**Issue by casto101** [roguerb/pull-request-workshop#17]
As a very beginner-friendly open source project, I think it'd be awesome for this community to adopt a code of conduct. Some comments on this project have been less than friendly. :( 

I'm a big fan of the [Contributor Covenant](http://contributor-covenant.org/) but definitely open to alternatives. Has anyone else seen open source codes of conduct that would be appropriate for this project?

**Comment by seanculver** [comment]
👍 We want this repository to be open and friendly for all.

**Comment by conroywhitney** [comment]
I'm a fan of ruby's code of conduct (https://www.ruby-lang.org/en/conduct/) pasted below:

> This document provides community guidelines for a safe, respectful, productive, and collaborative place for any person who is willing to contribute to the Ruby community. It applies to all “collaborative space”, which is defined as community communications channels (such as mailing lists, submitted patches, commit comments, etc.).
> - Participants will be tolerant of opposing views.
> - Participants must ensure that their language and actions are free of personal attacks and disparaging personal remarks.
> - When interpreting the words and actions of others, participants should always assume good intentions.
> - Behaviour which can be reasonably considered harassment will not be tolerated.

**Comment by conroywhitney** [comment]
BTW I personally am 👍 for adding a code of conduct, and I have seen some of the comments you're referring to @casto101. Thanks for pointing those out. I'll address those.

Does anyone feel strongly that we should _not_ implement a CoC? e.g., I'm not a huge fan of the Contributor Covenant one above because it places undue burden / punishment on the maintainers in my own personal opinion.

Does anyone have any other examples of CoCs, or want to discuss implementing a CoC in general?

**Comment by seanculver** [comment]
@conroywhitney I've created this https://github.com/roguerb/pull-request-workshop/pull/18 for this issue.

**Comment by seanculver** [comment]
@conroywhitney What issues do you have with the CoC? in the PR?

**Comment by seanculver** [comment]
@conroywhitney If you feel strongly about ruby's code of conduct, I'm ok with that. Can you create a PR for that.

**Comment by mistertime** [comment]
MINSWAN, anyone?

**Comment by conroywhitney** [comment]
I'm a fan of [MINISWAN](https://en.wikipedia.org/wiki/MINASWAN); however, the ruby community had [a very, very, very long discussion](https://bugs.ruby-lang.org/issues/12004) about whether or not to adopt an actual CoC and came up with some interesting points. The CoC pasted above was what Matz eventually adopted. So it's kinda the new MINISWAN 😄

**Comment by conroywhitney** [comment]
If everyone's cool with using the Ruby CoC, I'll create a PR for that.

@casto101 -- since you opened this issue, I'd love to hear from you one last time.

**Comment by casto101** [comment]
Yeah, the Ruby CoC works for me @conroywhitney :)

**Comment by conroywhitney** [comment]
@casto101 -- when you get a chance, would you review #20? Thanks!

**Comment by conroywhitney** [comment]
Thanks for everyone's feedback! Closing RE: PR #20
