### ISSUE TITLE
Spelling in readme is terrible

### ISSUE THREAD

**Issue by casto101** [roguerb/pull-request-workshop#3]
Tons of spelling errors in the readme

**Comment by conroywhitney** [comment]
@casto101 Their's like a 100 words in there. Could you be more specific? Thanks!

**Comment by seanculver** [comment]
Pull requests much appreciated! :)

**Comment by casto101** [comment]
The first paragraph of the Readme is where the typos are! :)

**Comment by conroywhitney** [comment]
Closing since we merged in #7. Thanks @casto101!
