### ISSUE TITLE
multiply is doing add in roge math.

### ISSUE THREAD

**Issue by RacheleJohnson** [roguerb/pull-request-workshop#9]
I saw in the roge_math file that it was saying   def self.multiply(a, b)
a + b. you can not multiply a+b

**Comment by conroywhitney** [comment]
Hey @RacheleJohnson. Thanks for pointing this out!

Would you please create a new Pull Request that fixes this method, as well as updates the specs so this issue doesn't crop up again in the future?

Thanks!

**Comment by conroywhitney** [comment]
Closing per PR #19. Thanks @RacheleJohnson! 👍
